version: '3.8'

services:
  # Keycloak Identity Provider
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: keycloak-sso
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-file
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
    ports:
      - "8080:8080"
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./demo-realm.json:/opt/keycloak/data/import/demo-realm.json
      - keycloak_data:/opt/keycloak/data
      # Mount custom provider JAR
      - ./keycloak-customization/target/keycloak-custom-extensions.jar:/opt/keycloak/providers/keycloak-custom-extensions.jar
      # Mount custom theme
      - ./keycloak-themes/spicy-theme:/opt/keycloak/themes/spicy-theme
    networks:
      - saml-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/realms/demo || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  saml-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  keycloak_data:
