#!/bin/bash

echo "🧪 Testing Registration with WebAuthn Encryption"
echo "================================================"
echo ""
echo "📋 Pre-requisites Checklist:"
echo ""
echo "  □ Keycloak is running (http://localhost:8080)"
echo "  □ Theme deployed (custom-registration-theme)"
echo "  □ Theme activated in Realm settings → Themes"
echo "  □ User registration enabled in Realm settings → Login"
echo "  □ You have a hardware security key (YubiKey, etc.)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔗 Test URLs:"
echo ""
echo "1. Registration Page:"
echo "   http://localhost:8080/realms/demo/protocol/openid-connect/registrations?client_id=account&response_type=code"
echo ""
echo "2. Admin Console:"
echo "   http://localhost:8080"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🧪 Test Scenarios:"
echo ""
echo "TEST 1: Normal Registration (Without Encryption)"
echo "  1. Open registration page"
echo "  2. Fill all fields"
echo "  3. DON'T check the encryption checkbox"
echo "  4. Click 'Register'"
echo "  5. ✅ Should register normally"
echo ""
echo "TEST 2: Registration WITH Encryption"
echo "  1. Open registration page"
echo "  2. Fill all fields (including phone & address)"
echo "  3. ✅ CHECK the 'Encrypt with security key' checkbox"
echo "  4. Click 'Register'"
echo "  5. Status should show: 'Please touch your security key...'"
echo "  6. Touch your YubiKey/security key"
echo "  7. Status should show: 'Security key registered!'"
echo "  8. Status should show: 'Encrypting sensitive data...'"
echo "  9. Status should show: 'Data encrypted successfully!'"
echo " 10. ✅ Form should submit"
echo ""
echo "TEST 3: Verify Encrypted Data Stored"
echo "  1. Login to Admin Console: http://localhost:8080"
echo "  2. Go to: Users → View all users"
echo "  3. Click on the newly registered user"
echo "  4. Click 'Attributes' tab"
echo "  5. ✅ Should see:"
echo "     - encrypted_payload: {json with encrypted phone/address}"
echo "     - webauthn_credential_id: {base64 string}"
echo "     - encryption_salt: {base64 string}"
echo ""
echo "TEST 4: Error Handling (Cancel WebAuthn)"
echo "  1. Open registration page"
echo "  2. Fill all fields"
echo "  3. Check encryption checkbox"
echo "  4. Click 'Register'"
echo "  5. When prompted for security key, CANCEL or wait for timeout"
echo "  6. Should show error message"
echo "  7. Should offer option to proceed without encryption"
echo "  8. ✅ Click OK to proceed without encryption"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔍 Debug Tips:"
echo ""
echo "  • Open Browser Console (F12) to see detailed logs"
echo "  • Look for messages starting with ✅, ❌, 🔐"
echo "  • Check Network tab for form submission"
echo "  • Verify user attributes in Keycloak Admin Console"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

read -p "Press Enter to open registration page in browser..."

# Try to open browser
if command -v xdg-open > /dev/null; then
    xdg-open "http://localhost:8080/realms/demo/protocol/openid-connect/registrations?client_id=account&response_type=code"
elif command -v open > /dev/null; then
    open "http://localhost:8080/realms/demo/protocol/openid-connect/registrations?client_id=account&response_type=code"
else
    echo "Please open this URL manually:"
    echo "http://localhost:8080/realms/demo/protocol/openid-connect/registrations?client_id=account&response_type=code"
fi
